<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_PurchaseHistoryDetailsRate</name>
   <tag></tag>
   <elementGuidId>0959a9a4-c3f0-4b63-b738-8195f006e2fd</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SGD $50.00 / Unit 1 per hour</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyPrintDiv&quot;)/div[@class=&quot;purhstdtls-content-sec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;purhstdtls-col-sec&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;purhstdtls-delvry-sec&quot;]/div[@class=&quot;purhstdtls-delvry-timesec&quot;]/div[5]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
