<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LeaveAFeedback</name>
   <tag></tag>
   <elementGuidId>6ee90848-3a65-4fb1-9fa8-83f6721fb2b0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW2Fu8x5UOr8EtM8HvGmXG4J5uA59Fr5kbK405sLVA-2B3qgP3Zv2YZp4q81r0GLNT8oRw4rAgifz-2BNRLco0I-2FChRk27iO5QJYjpvsWd-2B1Z-2BQGYKP9CXwnSNyhg9Pd-2Fml0g-2Bw-3D-3D_OAQ4iIHwr000BAjM8fM-2BAFgCyy8fridlzCQkQq0rLT-2B-2BOv9o1-2Fk96AsisrlIDyudt-2BrckkD5hGPMp73r7PvdEJJqS2nCNxS6Y18ut870MsMzluDd1QNpfE63jp6KrtqSlW62szoYFfJGAkadW7hKaSEbrbh-2FclCVUGyOf62T5cVQxpM6sJs4o3iVtVoeFX5ZBqlF-2FFcPjsjICeH-2FeNlayqFwBUTNOAxz9KJdfEFFkRM-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dW2Fu8x5UOr8EtM8HvGmXG4J5uA59Fr5kbK405sLVA-2B3qgP3Zv2YZp4q81r0GLNT8oRw4rAgifz-2BNRLco0I-2FChRk27iO5QJYjpvsWd-2B1Z-2BQGYKP9CXwnSNyhg9Pd-2Fml0g-2Bw-3D-3D_OAQ4iIHwr000BAjM8fM-2BAFgCyy8fridlzCQkQq0rLT-2B-2BOv9o1-2Fk96AsisrlIDyudt-2BrckkD5hGPMp73r7PvdEJJqS2nCNxS6Y18ut870MsMzluDd1QNpfE63jp6KrtqSlW62szoYFfJGAkadW7hKaSEbrbh-2FclCVUGyOf62T5cVQxpM6sJs4o3iVtVoeFX5ZBqlF-2FFcPjsjICeH-2FeNlayqFwBUTNOAxz9KJdfEFFkRM-3D&amp;source=gmail&amp;ust=1562717518853000&amp;usg=AFQjCNFdktZIQsyx17OceLKH4n-R_IgLLA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave a feedback</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div[1]/div/div/div/div/div[1]/div[2]/div[3]/div[3]/div[1]/div[2]/div[2]/div[2]/div[5]/a</value>
   </webElementProperties>
</WebElementEntity>
