<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_Item</name>
   <tag></tag>
   <elementGuidId>9bc33fba-255b-43c8-b439-926865313a27</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ci3.googleusercontent.com/proxy/jqU6iCpkVr3TjRvi2OR8f7P8rmoB57vnemcbnAOQGAIJ74-UBC9_Xekl_ySqnrvtTMU2THYxRSdXP8AXx5O8PAEbQ5WLVifKuonZXxBtdFC7BUx6oSWIfXOAD3e03URyJD791PBb4SDB2R_5VII=s0-d-e1-ft#https://0704spaceth1.test.arcadier.io/images/items/item-60231-636978849803179879-TDJQZC.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CToWUd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div[1]/div/div/div/div/div[1]/div[2]/div[3]/div[3]/div[1]/div[2]/div[2]/div[2]/div[4]/table/tbody/tr/td[1]/img</value>
   </webElementProperties>
</WebElementEntity>
