<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_StartShopping</name>
   <tag></tag>
   <elementGuidId>fd3acbfe-ca38-46c0-8ea5-f55e96e75752</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW7z01BLCPmbN-2FVMVYEkzquLdxuuIjzUvBDXj9TELxjNV_K-2FcwX5XzPKzu-2BtkaX5DiIpQY-2BJjfr7M1V-2BGf6qcyxeKrNgpRV0usZlFeKXrMAVQBphTWaxadAAH3gZM8Otb31xf4nE7TfrDsW3IfDP-2FdQG8OOI8LKhGd8LQ5lDqDPeUC0DkgiR2Yf8o4633FE4CV2sfXgQmFMuui6XVa2ceCa6JR-2BJCahtPqjpcGOUDM7EW1DodquApaCLaAsQm70iS13KnMkMzzcpCQmhB-2FvGafjKA-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dW7z01BLCPmbN-2FVMVYEkzquLdxuuIjzUvBDXj9TELxjNV_K-2FcwX5XzPKzu-2BtkaX5DiIpQY-2BJjfr7M1V-2BGf6qcyxeKrNgpRV0usZlFeKXrMAVQBphTWaxadAAH3gZM8Otb31xf4nE7TfrDsW3IfDP-2FdQG8OOI8LKhGd8LQ5lDqDPeUC0DkgiR2Yf8o4633FE4CV2sfXgQmFMuui6XVa2ceCa6JR-2BJCahtPqjpcGOUDM7EW1DodquApaCLaAsQm70iS13KnMkMzzcpCQmhB-2FvGafjKA-3D&amp;source=gmail&amp;ust=1562390129002000&amp;usg=AFQjCNFlRVXo-jDNTa9NqH5_4nKKivjNAg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>START SHOPPING</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:ni&quot;)/div[2]/div[2]/div[2]/div[4]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
