<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>skip_step</name>
   <tag></tag>
   <elementGuidId>eb2b737a-957c-472a-825d-4b6af28ff6b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;merch&quot;]/div[2]/span/div/div/div[1]/div/div/div/div/div[2]/div/span/a</value>
   </webElementProperties>
</WebElementEntity>
