<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Settings</name>
   <tag></tag>
   <elementGuidId>39eb0272-4540-44cf-a246-6b861a80df5c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Settings</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merch&quot;)/div[@class=&quot;db-DashboardRoot&quot;]/span[1]/div[1]/div[@class=&quot;db-World-root&quot;]/div[@class=&quot;db-World-wrapper Box-root Flex-flex Flex-direction--column&quot;]/div[@class=&quot;db-World-scrollWrapper&quot;]/div[@class=&quot;db-World-sideNavContainer&quot;]/div[@class=&quot;db-SideNav-container Box-root Box-background--surface Padding-top--20 Padding-right--2 Flex-flex Flex-direction--column&quot;]/div[@class=&quot;db-SideNav-navSections Box-root&quot;]/div[@class=&quot;Box-root Flex-flex Flex-direction--column Flex-justifyContent--flexStart&quot;]/div[@class=&quot;Box-root Box-hideIfEmpty Margin-top--16&quot;]/ul[1]/li[3]/div[1]/div[@class=&quot;db-SideNav-item--root&quot;]/span[1]/ul[1]/li[4]/div[1]/a[1]/div[1]/div[@class=&quot;db-SideNav-icon-no_icon Box-root&quot;]/div[@class=&quot;NavItem Box-root Box-background--surface Padding-horizontal--4 Padding-vertical--2&quot;]/div[@class=&quot;Box-root Padding-left--32 Flex-flex Flex-alignItems--center&quot;]/span[@class=&quot;Text-color--dark Text-fontSize--14 Text-fontWeight--regular Text-lineHeight--20 Text-typeface--base Text-wrap--wrap Text-display--inline&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
