<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-toggle</name>
   <tag></tag>
   <elementGuidId>62df0fc7-477f-43a0-a1e2-be2d0b5ba3b9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-toggle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_dPU4A6DLhUqe2maK0ue3wA&quot;)/div[1]/div[1]/div[@class=&quot;main&quot;]/div[@class=&quot;seller-tab-area spacetime-tab-area&quot;]/div[@class=&quot;spacetime_tab-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/ul[1]/li[@class=&quot;tab-location completed&quot;]/div[@class=&quot;tab-content-header&quot;]/a[@class=&quot;toggle-tab&quot;]/i[@class=&quot;icon-toggle&quot;]</value>
   </webElementProperties>
</WebElementEntity>
