<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Connect</name>
   <tag></tag>
   <elementGuidId>346b0ba2-e2e9-4e1a-a769-4ce35a1f4470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;merch&quot;]/div[2]/span/div/div/div[1]/div/div[3]/div/div/div[2]/div/div[2]/div/div[3]/div/a/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;merch&quot;]/div[2]/span/div/div/div[1]/div/div[3]/div/div/div[2]/div/div[2]/div/div[3]/div/a/div/div/span</value>
   </webElementProperties>
</WebElementEntity>
