<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_130characters130characters1</name>
   <tag></tag>
   <elementGuidId>11823098-c316-468d-854c-b435b764a5fb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>130characters130characters130characters130characters130characters130characters130characters130characters130characters130</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;inbox-view&quot;]/div[@class=&quot;row-inbox new-message&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;row-table&quot;]/div[@class=&quot;inbox-cell inbox-descrption&quot;]/h5[1]</value>
   </webElementProperties>
</WebElementEntity>
