<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Admin Onboarding Only(BESPOKE)</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2019-12-06T13:50:33</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e5d07e2e-3915-4e42-b5f3-67d760df768a</testSuiteGuid>
   <testCaseLink>
      <guid>b4b4c108-85c6-4829-9952-6166882c42bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ADMIN/Onboarding/Admin_Onboarding_Create_Account</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b6418fd8-52af-4b77-b403-b79220f8cda0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ADMIN/Onboarding/Complete Onboarding</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df53115c-b33b-4919-b918-4366dbd42e95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41282077-4862-4c4e-b97e-b3b00cff4a53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>332ce3d3-4db1-434c-a0e5-9eecd53d3d5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d41bd923-1a56-4786-9b69-9560da36bdde</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a562b495-4ad2-4f58-8835-e254b1e25049</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f980e8bb-9440-4c91-b78c-2a4da2e43359</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22c1ab47-95e0-4c41-9be8-18c744904c43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c3de02f-cd53-4bdf-8ea4-887edf26c07f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ac36231-48a9-4d15-9164-b570c476b59b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33d1bbad-5334-456c-a546-a05e98e25825</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>331a0c48-3ee6-4819-b5f4-876432d734cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b26605f-911e-4591-ad8d-47d0e6cbc10a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0df9001a-11a5-4b6b-96a5-8ca3fcec6f91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b8e51c-67f4-4880-a863-091b4ad5e730</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ca630b1-79be-49a3-8d5a-13802e7670a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93b18a9c-0eb6-44f6-b3dd-57e49e8415e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6badb04c-23c6-4bba-b1ea-1630545aabdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a43551a-23d7-4c1c-97e5-c8b751dcb076</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4686fac-04f1-4664-84e2-b0596f0f2f66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ca0fbbc-a1bb-427e-93dd-909d1b87d36a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
