<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo_marketplace</name>
   <tag></tag>
   <elementGuidId>84c766c3-9f09-4197-b25d-d114aa843c0b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ci4.googleusercontent.com/proxy/xH3O--GX28RR3MBGXoyU9eu7Hvx8PAWJAr2DdYcmsn6_CqCHzf_5rTydRYCuSmH1GcbU6ty0jkruaCyZL5J_ChYY_b1BGTudG-WsSh-CZOiFU_AT_XjNRu_Wr3CQ4jHAlx1Q_dp6sahKQNOprlrQZRiTy_8ng7qmsD8NZexImm9_dg=s0-d-e1-ft#https://0322st01.test.arcadier.io/userdata/0322st01.test.arcadier.io/images/logo-0322st01.test.arcadier.io.jpeg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CToWUd a6T</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[3]/div[3]/div/div[2]/div[2]/div[2]/div[2]/img</value>
   </webElementProperties>
</WebElementEntity>
