<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_status</name>
   <tag></tag>
   <elementGuidId>2110f882-7c62-4a34-8090-ed558aa0efa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;blsl-list-tab2&quot;)/div[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;sts-interested&quot;][count(. | //td[@data-title = 'Status' and @class = 'sts-interested' and (text() = 'Interested' or . = 'Interested')]) = count(//td[@data-title = 'Status' and @class = 'sts-interested' and (text() = 'Interested' or . = 'Interested')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Status</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sts-interested</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interested</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blsl-list-tab2&quot;)/div[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;sts-interested&quot;]</value>
   </webElementProperties>
</WebElementEntity>
