<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_cke_wysiwyg_frame cke_r</name>
   <tag></tag>
   <elementGuidId>93d1b996-435e-403a-ae71-116359fb576b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/p</value>
   </webElementProperties>
</WebElementEntity>
