<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>texteditor_Content</name>
   <tag></tag>
   <elementGuidId>fff5416e-2975-4c40-9b45-9e9d92fc119f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cke_editor1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cke_1 cke cke_reset cke_chrome cke_editor_editor1 cke_ltr cke_browser_webkit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>application</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cke_editor1_arialbl</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rich Text Editor, editor1Editor toolbarsClipboard/Undo UndoKeyboard shortcut Ctrl+Z RedoKeyboard shortcut Ctrl+YEditing Select AllBasic Styles BoldKeyboard shortcut Ctrl+B ItalicKeyboard shortcut Ctrl+I UnderlineKeyboard shortcut Ctrl+U Strikethrough Subscript SuperscriptParagraph Insert/Remove Numbered List Insert/Remove Bulleted List Decrease Indent Increase Indent Block Quote Align Left Center Align Right JustifyLinks LinkKeyboard shortcut Ctrl+K UnlinkInsert Image Table Insert Horizontal Line Smiley Insert Special CharacterStylesFormatNormalFontFontSizeSizeColors Text Color Background ColorPress ALT 0 for help◢</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cke_editor1&quot;)</value>
   </webElementProperties>
</WebElementEntity>
