<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_link</name>
   <tag></tag>
   <elementGuidId>e49d548a-f5ab-452f-bb10-f5a869081be1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[3]/div[3]/div/div[1]/div[2]/div[2]/div[3]/p[2]/a[count(. | //a[(text() = 'Please reset your password by clicking here' or . = 'Please reset your password by clicking here')]) = count(//a[(text() = 'Please reset your password by clicking here' or . = 'Please reset your password by clicking here')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW7z01BLCPmbN-2FVMVYEkzquKyMQuGvaBF12zwQoOzy8CtelqKosCWFaPOt4HE4bHVlO2VOHPLceQBu2XV-2BQ0zB83iFk85OR562QtRAGmY55mZBNKDDJ5C-2FvESbtIt6XjtRvVhFg05R5gf6TJMI7ghRvY-2FOQXUSg2dS0cmdw9vOZI4cOkeHoyvw4EOIUQEZvjrxE02kCOm6PHsck333995Tcyw3pw9xcBCNYYZM2Bu3aJT4oJe4V-2FEcI1zCZFc70opfMmHo2hxJY5H9D-2FpgS-2BxfMLf9OzwoFmG6vE-2Bj886nOa8-2BrsscxxXp8ZQj1xCwpQK8ryz6ifwWBpM-2BwwJX2ukKJM-3D_K-2FcwX5XzPKzu-2BtkaX5DiIpQY-2BJjfr7M1V-2BGf6qcyxeL2kjyERsP7nU1ewQEnhd6Z0DGMhVQ-2F6DJz-2BUSTgrdllN-2Fzn1LpdwFgLs2CdY25D9U024iSMPo1OyVUYTKGaph0eY7z1qZ0RKm7UjrbHouyefvFaDyFq-2FKjcqEN20qWnyQ7nQX176LnHYflwGB4MWNq6yB3VJtWhdJ-2F3yl0aDQ-2F18PzPnai9nK7T-2BelpaqOVH4-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dW7z01BLCPmbN-2FVMVYEkzquKyMQuGvaBF12zwQoOzy8CtelqKosCWFaPOt4HE4bHVlO2VOHPLceQBu2XV-2BQ0zB83iFk85OR562QtRAGmY55mZBNKDDJ5C-2FvESbtIt6XjtRvVhFg05R5gf6TJMI7ghRvY-2FOQXUSg2dS0cmdw9vOZI4cOkeHoyvw4EOIUQEZvjrxE02kCOm6PHsck333995Tcyw3pw9xcBCNYYZM2Bu3aJT4oJe4V-2FEcI1zCZFc70opfMmHo2hxJY5H9D-2FpgS-2BxfMLf9OzwoFmG6vE-2Bj886nOa8-2BrsscxxXp8ZQj1xCwpQK8ryz6ifwWBpM-2BwwJX2ukKJM-3D_K-2FcwX5XzPKzu-2BtkaX5DiIpQY-2BJjfr7M1V-2BGf6qcyxeL2kjyERsP7nU1ewQEnhd6Z0DGMhVQ-2F6DJz-2BUSTgrdllN-2Fzn1LpdwFgLs2CdY25D9U024iSMPo1OyVUYTKGaph0eY7z1qZ0RKm7UjrbHouyefvFaDyFq-2FKjcqEN20qWnyQ7nQX176LnHYflwGB4MWNq6yB3VJtWhdJ-2F3yl0aDQ-2F18PzPnai9nK7T-2BelpaqOVH4-3D&amp;source=gmail&amp;ust=1562398605125000&amp;usg=AFQjCNF5ZFfXtpQP_5Z-f29qyewlL4dMfA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please reset your password by clicking here</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[3]/div[3]/div/div[1]/div[2]/div[2]/div[3]/p[2]/a</value>
   </webElementProperties>
</WebElementEntity>
