<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1img</name>
   <tag></tag>
   <elementGuidId>d3c3d4af-8efe-4a9e-a2de-93afb3cb61d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//section/div/div/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/items/item-53137-636742161936688315-18cV4D.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/a/img</value>
   </webElementProperties>
</WebElementEntity>
