<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClickHere_Button</name>
   <tag></tag>
   <elementGuidId>11320034-b65e-48d8-b14f-275d270cbf65</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrivateMarketplaceManager.ShowSignUpForm('singup')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click here to let us know!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pvt-login-main&quot;)/div[@class=&quot;prvt-login-midsec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;prvt-login-midwrapper&quot;]/div[@class=&quot;col-md-6 prvt-login-mid-l&quot;]/div[@class=&quot;prvt-login-inner-left active&quot;]/div[@class=&quot;prvtlogin-click-here-txt&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
