<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LearnMore_Button</name>
   <tag></tag>
   <elementGuidId>27a6d891-1682-449e-aedb-c17ea72f6661</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prvtlogin-right-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://1008sbth1.test.arcadier.io/admin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learn More</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pvt-login-main&quot;)/div[@class=&quot;prvt-login-midsec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;prvt-login-midwrapper&quot;]/div[@class=&quot;col-md-6  prvt-login-mid-r&quot;]/div[@class=&quot;prvt-login-inner-right&quot;]/div[@class=&quot;prvtlogin-rightbtn-sec&quot;]/a[@class=&quot;prvtlogin-right-btn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
