<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SignInSeller_Button</name>
   <tag></tag>
   <elementGuidId>5576443f-7159-482d-80a0-ee0e313d1fb0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>prvtlogin-left-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrivateMarketplaceManager.ShowSignUpForm('singin', 'seller')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in as Seller</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pvt-login-main&quot;)/div[@class=&quot;prvt-login-midsec&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;prvt-login-midwrapper&quot;]/div[@class=&quot;col-md-6 prvt-login-mid-l&quot;]/div[@class=&quot;prvt-login-inner-left active&quot;]/div[@class=&quot;prvtlogin-lefttbtn-sec&quot;]/a[@class=&quot;prvtlogin-left-btn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
