<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Dashboard</name>
   <tag></tag>
   <elementGuidId>fe76f676-beb4-4f29-beaa-b4fdfb7efbc7</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DASHBOARD</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_zZntpWPSSEqV4WItuJCvQ&quot;)/div[1]/div[@class=&quot;seller-titlearea&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/h1[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
