<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Notice</name>
   <tag></tag>
   <elementGuidId>a6725fe2-b0e8-4e97-8c27-b715e582cdab</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notice</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_sjjS9giMfkKK8fWjFzdVUQ&quot;)/div[@class=&quot;col-sm-9 main-content ann&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;notice_area&quot;]/div[@class=&quot;heading&quot;]/h4[1]</value>
   </webElementProperties>
</WebElementEntity>
