<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Browse_Step6</name>
   <tag></tag>
   <elementGuidId>6886bc08-cc06-473e-a056-d1aa3f82e87f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>browse-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browse</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketplace-cover-picture&quot;)/div[@class=&quot;col-md-8 col-sm-12 col-md-offset-2&quot;]/div[@class=&quot;form-group file-group&quot;]/a[@class=&quot;cmn-browse-btnlink model-btn&quot;]/span[@class=&quot;browse-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
