<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_payment-status-color2</name>
   <tag></tag>
   <elementGuidId>f3bd340c-769f-4ed5-90b1-cb3ae99c9200</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tbLanguageRow&quot;]/tr[4]/td[3]/div[1][count(. | //*[@class = 'payment-status-color2']) = count(//*[@class = 'payment-status-color2'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-status-color2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tbLanguageRow&quot;]/tr[4]/td[3]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
