<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_Item</name>
   <tag></tag>
   <elementGuidId>e5485295-5aba-41bf-ae08-d8414948c944</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ci4.googleusercontent.com/proxy/xXgDoozjdQvtjj1FiPwTAH5tTYivGp_OOAeYsUnrJBB-QItdLnlrexlnaZH0cphBRceUtjpN2RzvPQruQmw0qdCcIuTRBjkecrtJLzBaT4lYZ7ys4UXdQW0QWWH9Htb26u3y1QW5Dgw=s0-d-e1-ft#https://time23.test.arcadier.io/images/items/item-59901-636941784727190648-8u2Q0h.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CToWUd a6T</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[3]/div[3]/div/div[2]/div[2]/div[2]/div[5]/table/tbody/tr/td[1]/img</value>
   </webElementProperties>
</WebElementEntity>
