<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_Subtotal</name>
   <tag></tag>
   <elementGuidId>3fd67be5-240a-4ed7-9a29-069095e5babb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subtotal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pay-info&quot;)/div[@class=&quot;subscription-pay-right subscription-pay-height&quot;]/div[@class=&quot;subs-content-layer&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;content-left&quot;]/p[1]</value>
   </webElementProperties>
</WebElementEntity>
