<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Upgrade</name>
   <tag></tag>
   <elementGuidId>b568d701-539d-4906-a8d7-7b24be0d7359</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-subs-purchase</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upgrade</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;period-day&quot;)/div[@class=&quot;subs-layer Starter&quot;]/div[@class=&quot;subs-layer-bottom&quot;]/div[@class=&quot;btn-subs-container&quot;]/a[1]/span[@class=&quot;btn-subs-purchase&quot;]</value>
   </webElementProperties>
</WebElementEntity>
