<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>arcadierlogoIG</name>
   <tag></tag>
   <elementGuidId>a84e421c-5dd0-4a6e-b1af-788f39885437</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6q-tv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://scontent-hkg3-2.cdninstagram.com/vp/08c6d6e4dd8007704eee5314c9c1d3e0/5CAC72F5/t51.2885-19/14294886_287534008294895_7982631116903284736_a.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>arcadier's profile picture</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-root&quot;)/section[@class=&quot;_9eogI E3X2T&quot;]/main[@class=&quot;SCxLW  o64aR&quot;]/div[@class=&quot;v9tJq&quot;]/header[@class=&quot;vtbgv&quot;]/div[@class=&quot;XjzKX&quot;]/div[@class=&quot;RR-M- h5uC0&quot;]/span[@class=&quot;_2dbep&quot;]/img[@class=&quot;_6q-tv&quot;]</value>
   </webElementProperties>
</WebElementEntity>
