<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Payment</name>
   <tag></tag>
   <elementGuidId>f867715e-cdd5-423c-aefd-b44e2f10810e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDetailContainer&quot;)/div[@class=&quot;row wrap-panel&quot;]/div[@class=&quot;col-sm-6 col-md-6&quot;]/div[@class=&quot;w-panel-box&quot;]/ul[@class=&quot;w-list-items&quot;]/li[4]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
