<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_option2</name>
   <tag></tag>
   <elementGuidId>10cd5380-119f-494f-9b7e-4b6c91ecba5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div[3]/div/div[1]/div[2]/div/form/div/div[7]/div/ul/li[2]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dropdown-opt-draggble&quot;]/li[2]/div/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
