<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>upgrade_basic</name>
   <tag></tag>
   <elementGuidId>58beef7e-c97c-4c5e-b1e6-d4be629a13cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[2]/div[2]/div[3]/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[2]/div[2]/div[3]/div/a/span</value>
   </webElementProperties>
</WebElementEntity>
