<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paypal_email</name>
   <tag></tag>
   <elementGuidId>bdd0bfd5-4ad5-4e78-aa2b-22abc7332032</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hiveboxstaging01@yopmail.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDetailContainer&quot;)/div[@class=&quot;row wrap-panel&quot;]/div[@class=&quot;col-sm-6 col-md-6&quot;]/div[@class=&quot;w-panel-box&quot;]/ul[@class=&quot;w-list-items&quot;]/li[4]/table[1]/tbody[1]/tr[2]/td[2]</value>
   </webElementProperties>
</WebElementEntity>
