<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo_marketplace</name>
   <tag></tag>
   <elementGuidId>43b549e3-fd59-41b3-a76e-068da0aa5523</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ci6.googleusercontent.com/proxy/30aB4E0MKm4ybc9DXs4QtUdIsG3Hdf44cuWorNcPyLyR6s0I9pnMHWbXjFZtgwoN1NAhZ_V7qUVDQWdprq1tdKM9KzKmrneuLrKbiIPzmjpFeqjbdg1xAWaMn_D2L9-1OqEu63P7UvTogdDWuHcNUibI9K5amPncqf0lIojE=s0-d-e1-ft#https://0705st1.test.arcadier.io/userdata/0705st1.test.arcadier.io/images/logo-0705st1.test.arcadier.io.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CToWUd a6T</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:or&quot;)/div[2]/div[2]/div[2]/div[2]/img[@class=&quot;CToWUd a6T&quot;]</value>
   </webElementProperties>
</WebElementEntity>
