<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_UploadItemNow</name>
   <tag></tag>
   <elementGuidId>b0cea42d-a151-472a-a442-6b4d2aea5e55</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW7z01BLCPmbN-2FVMVYEkzquKHjT8jRKdQCVPujE5IVlSiuQ5blI4OFF686u95ABgweg-3D-3D_K-2FcwX5XzPKzu-2BtkaX5DiIpQY-2BJjfr7M1V-2BGf6qcyxeIeX86XBKQut-2B9fngXjYmR4vOKPd8xJBaNWj3qrsjfFRkuzI9k-2Bo3Bd-2FvsS71OVSx6KMJqOjDgGVWfi-2FkLe-2FXAQjXQ7XN9qEMn68R7W69kLYrGhCOP1M1MrnN84XAkU3z-2FUmHPaHS0jeAYeKtzVY1sBcc6DATOfFbFMg4p02iKGmez5HK2b0ZzDDRjmMXNFhVE-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dW7z01BLCPmbN-2FVMVYEkzquKHjT8jRKdQCVPujE5IVlSiuQ5blI4OFF686u95ABgweg-3D-3D_K-2FcwX5XzPKzu-2BtkaX5DiIpQY-2BJjfr7M1V-2BGf6qcyxeIeX86XBKQut-2B9fngXjYmR4vOKPd8xJBaNWj3qrsjfFRkuzI9k-2Bo3Bd-2FvsS71OVSx6KMJqOjDgGVWfi-2FkLe-2FXAQjXQ7XN9qEMn68R7W69kLYrGhCOP1M1MrnN84XAkU3z-2FUmHPaHS0jeAYeKtzVY1sBcc6DATOfFbFMg4p02iKGmez5HK2b0ZzDDRjmMXNFhVE-3D&amp;source=gmail&amp;ust=1562390128997000&amp;usg=AFQjCNHB0XfN0SHAHZEXh6C7FljdD1iCzg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UPLOAD ITEMS NOW!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:mc&quot;)/div[2]/div[2]/div[2]/div[4]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
