<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>merchant_all</name>
   <tag></tag>
   <elementGuidId>e13ed5e9-5153-43b4-95ea-45e5e926bf91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;dropdownMerchant&quot;]/li[2]/a/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>merchant_0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>div.main.template-sidebar div.col-sm-9.main-content div.page-content div div.filter-bar.page-topnav form.form-inline.form-filter div.f-btm div.row div.col-md-6.col-sm-6 div.row div.col-md-6 div.col-md-6 div.form-group.field-merchant.selectbox div.advanced-select div.dropdown.open ul#dropdownMerchant.dropdown-menu li a.x-check</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dropdownMerchant&quot;]/li[2]/a/label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>merchant_0</value>
   </webElementProperties>
</WebElementEntity>
