<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_dropdownOpt2</name>
   <tag></tag>
   <elementGuidId>e86a682f-ae83-48e7-92fb-241f8b65c9f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div[4]/div/div[1]/div[2]/div/form/div/div[9]/div/ul/li[2]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[8]/div/ul/li[2]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[8]/div/ul/li[2]/div/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
