<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox-opt4</name>
   <tag></tag>
   <elementGuidId>1d1747a2-a317-44b9-ac9f-30c996bc6350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;contactForm&quot;)/div[@class=&quot;form-field-controler&quot;]/div[@class=&quot;opt4 custom-field-opt active&quot;]/div[@class=&quot;custom-field-form&quot;]/ul[@id=&quot;dropdown-opt-draggble&quot;]/li[4]/div[@class=&quot;virtual-table&quot;]/div[@class=&quot;virtual-table-cell&quot;]/input[@class=&quot;required&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>400</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkbox-opt[]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactForm&quot;)/div[@class=&quot;form-field-controler&quot;]/div[@class=&quot;opt4 custom-field-opt active&quot;]/div[@class=&quot;custom-field-form&quot;]/ul[@id=&quot;dropdown-opt-draggble&quot;]/li[4]/div[@class=&quot;virtual-table&quot;]/div[@class=&quot;virtual-table-cell&quot;]/input[@class=&quot;required&quot;]</value>
   </webElementProperties>
</WebElementEntity>
