<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_item</name>
   <tag></tag>
   <elementGuidId>4b701c78-1d57-49bf-9578-97568e48b263</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/items/item-62788-637080811512073408-TbjP1w.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartMenu&quot;)/li[1]/div[@class=&quot;cart-item-wrapper&quot;]/div[@class=&quot;cart-item-preview&quot;]/a[1]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
