<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe___privateStripeFrame5</name>
   <tag></tag>
   <elementGuidId>b9d7e2ba-8cfa-4f14-af57-f5f629b0668a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;card-element&quot;]/div/iframe[count(. | //iframe[@name = '__privateStripeFrame5' and @ref_element = 'Object Repository/ADMIN/Subscription/Payment/iframe___privateStripeFrame5']) = count(//iframe[@name = '__privateStripeFrame5' and @ref_element = 'Object Repository/ADMIN/Subscription/Payment/iframe___privateStripeFrame5'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>__privateStripeFrame5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowpaymentrequest</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://js.stripe.com/v3/elements-inner-card-f6d4daf53ab44ddc4b9f013359f4c42c.html#hidePostalCode=true&amp;style[base][color]=%23303238&amp;style[base][fontSize]=16px&amp;style[base][lineHeight]=48px&amp;style[base][fontSmoothing]=antialiased&amp;style[base][::placeholder][color]=%23ccc&amp;style[invalid][color]=%23e5424d&amp;style[invalid][:focus][color]=%23303238&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;origin=https%3A%2F%2F0709sr.test.arcadier.io&amp;referrer=https%3A%2F%2F0709sr.test.arcadier.io%2Fadmin%2Fsubscription%2Fupgrade%3FplanId%3D6&amp;controllerId=__privateStripeController1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Secure payment input frame</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;card-element&quot;]/div/iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>root</value>
   </webElementProperties>
</WebElementEntity>
