<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Browse_Button</name>
   <tag></tag>
   <elementGuidId>58b80b0c-d925-4af3-8f1e-ef3ccc662d27</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browse</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;81885&quot;)/div[@class=&quot;full-width&quot;]/div[@class=&quot;browse-control&quot;]/a[@class=&quot;model-btn&quot;]/div[@class=&quot;browse-btn&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
