<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_EN</name>
   <tag></tag>
   <elementGuidId>aa479405-11b0-4258-b1a3-4cf8563a1180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//*[(text() = 'FR' or . = 'FR')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'ES' or . = 'ES')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dd-selected-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ES</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectLanguage&quot;)/div[@class=&quot;dd-select&quot;]/a[@class=&quot;dd-selected&quot;]/label[@class=&quot;dd-selected-text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
