<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SellerSettings</name>
   <tag></tag>
   <elementGuidId>d09d19a5-d4b8-4a57-af09-319065850371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[3]/div[3]/div/div[2]/div/div[2]/div[4]/a/span[count(. | //a[(text() = 'Seller Settings' or . = 'Seller Settings')]) = count(//a[(text() = 'Seller Settings' or . = 'Seller Settings')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dWwNxLpX-2B2TZf-2BUZV292l8nHta2uURYr-2BuxxisCel3ZYTQGbn3kXHpKITZwAYIQm-2F3oHblPhlubgDyegjKfYdA6TxcCjv0NwuRqSZP0TUGkVfkbJg2Ewum9uL8OAKukxPxA-3D-3D_K-2FcwX5XzPKzu-2BtkaX5DiIpQY-2BJjfr7M1V-2BGf6qcyxeJHD29iM3Q3hssRVNlx01utQjrwzdxRJCs6hGVcRF55U49r4B48K4pxBWV6azBYkCj5jxXqrUCfA0LsJm5KpM-2BDKndR55ty1MzmeHw-2Fwl4dVhuz1Z5ytzyYgDPljOdp1X8M3WSud3qsRiMHu5OKLJFSxKJ3oy1xzPno37wYlGlN-2Bs6b9f1GDaU8wGs1nFMsCYM-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dWwNxLpX-2B2TZf-2BUZV292l8nHta2uURYr-2BuxxisCel3ZYTQGbn3kXHpKITZwAYIQm-2F3oHblPhlubgDyegjKfYdA6TxcCjv0NwuRqSZP0TUGkVfkbJg2Ewum9uL8OAKukxPxA-3D-3D_K-2FcwX5XzPKzu-2BtkaX5DiIpQY-2BJjfr7M1V-2BGf6qcyxeJHD29iM3Q3hssRVNlx01utQjrwzdxRJCs6hGVcRF55U49r4B48K4pxBWV6azBYkCj5jxXqrUCfA0LsJm5KpM-2BDKndR55ty1MzmeHw-2Fwl4dVhuz1Z5ytzyYgDPljOdp1X8M3WSud3qsRiMHu5OKLJFSxKJ3oy1xzPno37wYlGlN-2Bs6b9f1GDaU8wGs1nFMsCYM-3D&amp;source=gmail&amp;ust=1562397421527000&amp;usg=AFQjCNH8QhKclN64KygdnVYh_YItGY5CKw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seller Settings</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[3]/div[3]/div/div[2]/div/div[2]/div[4]/a/span</value>
   </webElementProperties>
</WebElementEntity>
