<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo_marketplace</name>
   <tag></tag>
   <elementGuidId>795950f1-9dc7-4327-a85d-b2e17fa10d43</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ci3.googleusercontent.com/proxy/_jGSRxCJz2QhCZREGB-AY-shkHa4jLLXthhpu3txABFBaZeBqE26Ow39Zo-21ucJARUnnyTxbdEvmlq86MfJLmA6lSKn446gfi-oE36oTmXbWCzYyJW1DDlk5L4YLtQhlR9CBwsSD3akCVSjrAqBRRze32Fww0UEaUZxRQ=s0-d-e1-ft#https://time23.test.arcadier.io/userdata/time23.test.arcadier.io/images/logo-time23.test.arcadier.io.jpeg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CToWUd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[3]/div[3]/div/div[2]/div[2]/div[2]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
