<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>upgrade_scale</name>
   <tag></tag>
   <elementGuidId>f6814381-0fdf-42a2-a0ae-d18fb367ec31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[3]/div[4]/div[3]/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[3]/div[4]/div[3]/div/a/span</value>
   </webElementProperties>
</WebElementEntity>
