<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_PrivateSettings</name>
   <tag></tag>
   <elementGuidId>56183d97-02a0-48e9-98e5-1664a1f931da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[3]/div[2]/div[3]/div[3]/div[1]/table/tbody/tr[1]/td[7]/div/label/span[2][count(. | //*[@class = 'onoffswitch-switch']) = count(//*[@class = 'onoffswitch-switch'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onoffswitch-switch</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div[3]/div[1]/table/tbody/tr[1]/td[7]/div/label/span[2]</value>
   </webElementProperties>
</WebElementEntity>
